### ISSUE TITLE
Initial development work roadmap

### ISSUE THREAD

**Issue by fotinakis** [percy/python-percy-client#5]
- [x] `create_build` API call
  - [x] tests 
  - [x] handle resources kwargs
- [x] `create_snapshot` API call
  - [x] tests 
- [x] `finalize_snapshot` API call
  - [x] tests 
- [x] `upload_resource` API call
  - [x] tests 
- [x] `finalize_build` API call + tests 
- [x] Allow `Config` object to be created and passed into client, and/or manually modified so that people can do something like `percy_client.config.default_widths = (1280, 375)`
- [x] Environment discovery logic
  - [x] `current_ci`
  - [x] `branch`
    - [x] Special Travis CI branch logic for Travis's terrible env logic.
  - [x] `pull_request_number`
  - [x] commit data (just `commit-sha` for now)
  - [x] `repo`
  - [x] `parallel_nonce`
  - [x] `parallel_total_shards`
- [x] Add tests to ensure encoding for binary resources works as intended.
- [x] Add tests to ensure encoding for unicode resources works as intended.
- [x] Utility method for handling 2/3 encoding compatibility.
- [x] Resource discovery: add a `Loader` class and the ability to create a list of `Resource` objects from `Loader().make_build_resources(root_dir='/foo/static', prepend_url="/_static/...version.../")`.
- [ ] Connection management and error handling for safely handling intermittent API failures without disrupting CI test runs.

After the above are complete, we'll have full API coverage.

Then, we'll need:
- [x] `Build()` convenience wrapper object, holds state for build ID and will be the public user interface for tests.
- [x] Some interface for selenium interaction, probably just a `driver` arg and calling `driver.page_source` to get the source HTML by default.
- [x] Resource discovery (slightly larger unknown, how do we automatically read all static resources? Rely on Django?)
- [x] At least basic documentation of how to use in python tests.
- [x] Release on pip.

**Comment by fotinakis** [comment]
The initial integration PR with Sentry is up, so I'm going to close this as complete!
https://github.com/getsentry/sentry/pull/3497
